import {CityName} from './constants.js';

const RATING_STARS = 5;
const DEFAULT_CITY = CityName.PARIS;
const COMMENTS_TO_SHOW = 10;
const NOTIFICATION_SHOW_TIMEOUT = 5000;
const MIN_COMMENT_LENGTH = 50;
const MAX_COMMENT_LENGTH = 300;

export {RATING_STARS, DEFAULT_CITY, COMMENTS_TO_SHOW, NOTIFICATION_SHOW_TIMEOUT, MIN_COMMENT_LENGTH, MAX_COMMENT_LENGTH};
